spring:
  datasource:
    url: jdbc:mysql://kirby-lib-db.cbyooaw40u3s.ap-northeast-2.rds.amazonaws.com:3306/kirbydb?serverTimezone=UTC&characterEncoding=utf8
    username: admin
    password: admin123

  jpa:
    show-sql: true

server:
  port: 8080

