server {
    listen 80;
    server_name kirbylib.duckdns.org;  # 도메인 연결 시 yourdomain.com 으로 바꿔도 됨

    # 정적 리소스 캐싱 (optional)
    location /static/ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # 리버스 프록시 설정
    location / {
        proxy_pass http://kirby-lib-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # 에러 로그 (optional)
    error_log /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;
}
